---
# 1. ХРАНИЛИЩА (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: homelab
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: homelab
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 10Gi
---
# 2. БАЗА ДАННЫХ (MySQL)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: homelab
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: ghost-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: ghost-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: ghost-password
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: homelab
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
---
# 3. ПРИЛОЖЕНИЕ (Ghost)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: homelab
spec:
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: https://ghost.nr64.art
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: ghost-user
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: ghost-password
        - name: database__connection__database
          valueFrom:
            secretKeyRef:
              name: mysql-ghost-secret
              key: ghost-database
        volumeMounts:
        - name: ghost-data
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-data
        persistentVolumeClaim:
          claimName: ghost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: homelab
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
    - port: 80
      targetPort: 2368
